version: 3


tasks:
   run:
     cmds:
       - docker-compose up --build
   build:
     cmds:
       - go build -o app ./cmd/server

   test:
     cmds:
       - go test ./... -v
   
   lint:
     cmds:
       - golangci-lint run
